---herdr-splits shared config file (generated artifact) + notation translator.
---Owns everything about `herdr-splits.conf`: path resolution, reading existing
---managed values, translating Neovim key notation to Herdr chord notation,
---and writing the resolved config back (atomically). Requires nothing else
---from this plugin (avoiding a require-cycle with config.lua).
---@class HerdrSplitsConf
local M = {}

-- Neovim modifier prefix -> Herdr modifier name.
local MOD = { C = 'ctrl', M = 'alt', A = 'alt', S = 'shift', D = 'cmd' }
-- Herdr's documented specials: lowercase the terminal key when present.
local SPECIAL = {
  left = 'left', right = 'right', up = 'up', down = 'down',
  enter = 'enter', ['return'] = 'enter', tab = 'tab',
  esc = 'esc', escape = 'esc', space = 'space', backspace = 'backspace',
  del = 'delete', delete = 'delete', home = 'home',
  ['end'] = 'end', pageup = 'pageup', pagedown = 'pagedown',
}

---Path to the shared herdr-splits config file (same file the Herdr-side
---scripts read). Honors HERDR_SPLITS_CONFIG and XDG_CONFIG_HOME. Resolves
---identically to the scripts' `$HERDR_PLUGIN_CONFIG_DIR/herdr-splits.conf`
---in the default case.
---@return string
function M.path()
  if vim.env.HERDR_SPLITS_CONFIG and vim.env.HERDR_SPLITS_CONFIG ~= '' then
    return vim.env.HERDR_SPLITS_CONFIG
  end
  local xdg = vim.env.XDG_CONFIG_HOME
  local base = (xdg and xdg:sub(1, 1) == '/') and xdg
      or ((vim.env.HOME or '~') .. '/.config')
  return base .. '/herdr/plugins/config/herdr-splits/herdr-splits.conf'
end

---Translate a Neovim key notation (e.g. `<C-h>`, `<M-Left>`, `h`) into the
---Herdr chord notation the scripts and `herdr pane send-keys` expect
---(e.g. `ctrl+h`, `alt+left`, `h`). Returns nil for modifier-only / empty
---input so callers can fall back to a per-direction default.
---@param nvim_key string
---@return string|nil
function M.to_herdr(nvim_key)
  if type(nvim_key) ~= 'string' or nvim_key == '' then return nil end
  if not nvim_key:match('^<.+>$') then return nvim_key:lower() end -- plain "h" -> "h"
  local inner = nvim_key:sub(2, -2)
  local mods, key = {}, nil
  for part in inner:gmatch('[^-]+') do
    local m = MOD[part:upper()]
    if m then
      mods[#mods + 1] = m
    else
      key = SPECIAL[part:lower()] or part:lower()
    end
  end
  if not key then return nil end
  mods[#mods + 1] = key
  return table.concat(mods, '+')
end

---Parse the shared config file for the 10 managed keys only. Returns
---`{ nav_keys={…}, resize_keys={…}, unzoom_on_nav=bool, nav_at_edge='wrap'|'stop' }`
---with only the keys present in the file set; last occurrence wins (matches
---the scripts' `tail -n 1`). Empty table if the file is missing.
---@return table
function M.read_managed()
  local f = io.open(M.path(), 'r')
  if not f then return {} end
  local out = { nav_keys = {}, resize_keys = {} }
  for line in f:lines() do
    local k, v = line:match('^%s*([%w_]+)%s*=%s*([^%s#]+)')
    if k and v then
      local dir = k:match('^nav_key_(%a+)$')
      if dir then
        out.nav_keys[dir] = v
      else
        dir = k:match('^resize_key_(%a+)$')
        if dir then
          out.resize_keys[dir] = v
        elseif k == 'unzoom_on_nav' then
          out.unzoom_on_nav = (v ~= 'false')
        elseif k == 'nav_at_edge' then
          out.nav_at_edge = (v == 'stop' and 'stop' or 'wrap')
        end
      end
    end
  end
  f:close()
  return out
end

---Write the full managed key set to the shared config with a generated-file
---header, atomically (temp file + os.rename) so a script never observes a
---partial write. Returns (true, nil) on success or (false, err) on failure;
---callers wrap in pcall so a write failure never crashes startup.
---@param resolved table resolved managed config (nav_keys, resize_keys, unzoom_on_nav, nav_at_edge)
---@return boolean ok, string|nil err
function M.write(resolved)
  local path = M.path()
  vim.fn.mkdir(vim.fn.fnamemodify(path, ':h'), 'p')
  local function chord(t, d, def)
    return t[d] or def
  end
  local lines = {
    '# herdr-splits plugin config — GENERATED by herdr-splits.nvim setup().',
    '# Configure via require("herdr-splits").setup({ ... }); do not edit by hand.',
    '# Any manual edit here is adopted once on the next setup(), then overwritten.',
    'nav_key_left='     .. chord(resolved.nav_keys,    'left',  'ctrl+h'),
    'nav_key_down='     .. chord(resolved.nav_keys,    'down',  'ctrl+j'),
    'nav_key_up='       .. chord(resolved.nav_keys,    'up',    'ctrl+k'),
    'nav_key_right='    .. chord(resolved.nav_keys,    'right', 'ctrl+l'),
    'resize_key_left='  .. chord(resolved.resize_keys, 'left',  'alt+h'),
    'resize_key_down='  .. chord(resolved.resize_keys, 'down',  'alt+j'),
    'resize_key_up='    .. chord(resolved.resize_keys, 'up',    'alt+k'),
    'resize_key_right=' .. chord(resolved.resize_keys, 'right', 'alt+l'),
    'unzoom_on_nav='    .. (resolved.unzoom_on_nav == false and 'false' or 'true'),
    'nav_at_edge='      .. (resolved.nav_at_edge == 'stop' and 'stop' or 'wrap'),
  }
  local tmp = path .. '.tmp'
  local f, err = io.open(tmp, 'w')
  if not f then
    vim.notify('herdr-splits: failed to open conf temp file: ' .. tostring(err), vim.log.levels.WARN)
    return false, err
  end
  f:write(table.concat(lines, '\n') .. '\n')
  f:close()
  local ok, rerr = os.rename(tmp, path)
  if not ok then
    vim.notify('herdr-splits: failed to write conf: ' .. tostring(rerr), vim.log.levels.WARN)
  end
  return ok, rerr
end

---Runnable self-check for the notation translator. Asserts on the documented
---mapping table; returns true on success. Intended for headless validation:
---`nvim --headless -c "lua assert(require('herdr-splits.conf')._selfcheck())" -c "qa"`.
---@return boolean
function M._selfcheck()
  local cases = {
    { '<C-h>', 'ctrl+h' }, { '<C-j>', 'ctrl+j' }, { '<C-k>', 'ctrl+k' }, { '<C-l>', 'ctrl+l' },
    { '<M-h>', 'alt+h' }, { '<M-Left>', 'alt+left' }, { '<S-Left>', 'shift+left' },
    { '<D-x>', 'cmd+x' }, { '<C-M-h>', 'ctrl+alt+h' }, { 'h', 'h' }, { '<Esc>', 'esc' },
  }
  for _, c in ipairs(cases) do
    local got = M.to_herdr(c[1])
    assert(got == c[2], ('to_herdr(%q)=%q want %q'):format(c[1], tostring(got), c[2]))
  end
  return true
end

return M
